name: 'Create a release'
description: 'Create a release for a tag in your repository'
author: 'easyware.io'
inputs:
  token:
    description: 'GitHub token'
    required: true
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, github.GITHUB_REF when a user pushes a new tag'
    required: true
  release_name:
    description: 'The name of the release. For example, v1.0.1'
    required: true
  body:
    description: 'Text describing the contents of the tag.'
    required: false
  body_path:
    description: 'Path to file with information about the tag.'
    required: false
  draft:
    description: 'true to create a draft (unpublished) release, false to create a published one. Default: false'
    required: false
  prerelease:
    description: 'true to identify the release as a prerelease. false to identify the release as a full release. Default: false'
    required: false
  commitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit'
    required: false
  owner:
    description: 'Owner of the repository if it is not the current one'
    required: false
  repo:
    description: 'Repository on which to release.  Used only if you want to create the release on another repo'
    required: false
  make_latest:
    description: 'Optional. Possible values are true, false and legacy'
    required: false
outputs:
  data:
    description: 'The release data'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: shield
  color: orange
